"""add guest fields to user

Revision ID: 19eaf9c0adf5
Revises: f4ef7c6a615b
Create Date: 2026-05-17 10:13:06.255934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19eaf9c0adf5'
down_revision = 'f4ef7c6a615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('demo_state', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('guest_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['guest_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('guest_token')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('demo_state')
        batch_op.drop_column('is_guest')

    # ### end Alembic commands ###
