"""add guest demo_remap to users

Revision ID: 39af69c2b5fd
Revises: b3dfd6b88a38
Create Date: 2026-05-17 19:59:15.719210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af69c2b5fd'
down_revision = 'b3dfd6b88a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_remap', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('demo_remap')

    # ### end Alembic commands ###
