"""Add dual tree cache

Revision ID: 6f60539dda6f
Revises: a77d08227a66
Create Date: 2026-05-10 19:21:29.602058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f60539dda6f'
down_revision = 'a77d08227a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_ui_tree', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cached_ui_tree_etag', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('cached_agent_tree', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cached_agent_tree_etag', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.drop_column('cached_agent_tree_etag')
        batch_op.drop_column('cached_agent_tree')
        batch_op.drop_column('cached_ui_tree_etag')
        batch_op.drop_column('cached_ui_tree')

    # ### end Alembic commands ###
