"""Add vault users and vault cache

Revision ID: 71682d0f7d44
Revises: 6f60539dda6f
Create Date: 2026-05-12 06:44:52.401358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71682d0f7d44'
down_revision = '6f60539dda6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vault_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_vault_list', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cached_vault_list_etag', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cached_vault_list_etag')
        batch_op.drop_column('cached_vault_list')

    op.drop_table('vault_access')
    # ### end Alembic commands ###
