"""replace chat tables with tasks

Revision ID: 7c398df191ff
Revises: 9e610349dec6
Create Date: 2026-05-09 20:39:12.143141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c398df191ff'
down_revision = '9e610349dec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context_node_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_message_context')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_vault_id'), ['vault_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_session_id_sort_order'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_author_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sort_order'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_status'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_vault_id'))

    op.drop_table('chat_sessions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_context',
    sa.Column('message_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('chat_message_context_message_id_fkey')),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('chat_message_context_version_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', 'version_id', name=op.f('chat_message_context_pkey'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vault_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='chat_sessions_owner_id_fkey'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], name='chat_sessions_vault_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_vault_id'), ['vault_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_owner_id'), ['owner_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('llm_model_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Explicit sort order for messages within a session.'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('chat_messages_author_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_id_sort_order'), ['session_id', 'sort_order'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_vault_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    # ### end Alembic commands ###
