"""add ai_summary and summary_is_current to nodes

Revision ID: 9e610349dec6
Revises: aba453bb5f09
Create Date: 2026-05-08 08:42:03.574803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e610349dec6'
down_revision = 'aba453bb5f09'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_is_current', sa.Boolean(), nullable=False, server_default='false'))  # ← add server_default

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('summary_is_current')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
