"""add task feedback columns

Revision ID: a130e84b416e
Revises: 71682d0f7d44
Create Date: 2026-05-13 07:40:49.819543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a130e84b416e'
down_revision = '71682d0f7d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('operations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('operations')
        batch_op.drop_column('finish_summary')

    # ### end Alembic commands ###
