"""Add FTS indexes and stored tsvector columns

Revision ID: a77d08227a66
Revises: 7c398df191ff
Create Date: 2026-05-10 17:11:43.348366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a77d08227a66'
down_revision = '7c398df191ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fts_summary_en', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(ai_summary,'')), 'C')", persisted=True), nullable=True))
        batch_op.add_column(sa.Column('fts_summary_de', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('german', coalesce(ai_summary,'')), 'C')", persisted=True), nullable=True))

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fts_en', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title,'')), 'A') || setweight(to_tsvector('english', coalesce(content,'')), 'B')", persisted=True), nullable=True))
        batch_op.add_column(sa.Column('fts_de', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('german', coalesce(title,'')), 'A') || setweight(to_tsvector('german', coalesce(content,'')), 'B')", persisted=True), nullable=True))

    # --- MANUAL ADDITION: Create GIN Indexes for blazing fast full-text search ---
    op.create_index('ix_versions_fts_en', 'versions', ['fts_en'], postgresql_using='gin')
    op.create_index('ix_versions_fts_de', 'versions', ['fts_de'], postgresql_using='gin')
    op.create_index('ix_nodes_fts_summary_en', 'nodes', ['fts_summary_en'], postgresql_using='gin')
    op.create_index('ix_nodes_fts_summary_de', 'nodes',['fts_summary_de'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- MANUAL ADDITION: Drop GIN Indexes ---
    op.drop_index('ix_nodes_fts_summary_de', table_name='nodes')
    op.drop_index('ix_nodes_fts_summary_en', table_name='nodes')
    op.drop_index('ix_versions_fts_de', table_name='versions')
    op.drop_index('ix_versions_fts_en', table_name='versions')

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_column('fts_de')
        batch_op.drop_column('fts_en')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('fts_summary_de')
        batch_op.drop_column('fts_summary_en')

    # ### end Alembic commands ###
