"""Replace string enums with IntEnum

Revision ID: db75cf6fc8f1
Revises: a130e84b416e
Create Date: 2026-05-17 08:31:07.747377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db75cf6fc8f1'
down_revision = 'a130e84b416e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               postgresql_using="CASE WHEN user_type = 'human' THEN 1 ELSE 2 END")

    with op.batch_alter_table('vault_access', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               postgresql_using="CASE WHEN role = 'editor' THEN 2 ELSE 1 END")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_access', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               postgresql_using="CASE WHEN role = 2 THEN 'editor' ELSE 'viewer' END")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using="CASE WHEN user_type = 1 THEN 'human' ELSE 'llm_assistant' END")

    # ### end Alembic commands ###