"""add demo_events

Revision ID: e61437fc8b9a
Revises: 39af69c2b5fd
Create Date: 2026-05-25 11:18:34.185743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61437fc8b9a'
down_revision = '39af69c2b5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_events_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_events_event_type'))

    op.drop_table('demo_events')
    # ### end Alembic commands ###
