"""Fix vault uniqueness constraint

Revision ID: f4ef7c6a615b
Revises: db75cf6fc8f1
Create Date: 2026-05-17 09:55:39.993274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ef7c6a615b'
down_revision = 'db75cf6fc8f1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        # Removed batch_op.f() to drop the exact implicit constraint name generated by Postgres
        batch_op.drop_constraint('vaults_name_key', type_='unique')
        batch_op.create_unique_constraint('uq_vault_name_per_user', ['owner_id', 'name'])


def downgrade():
    with op.batch_alter_table('vaults', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vault_name_per_user', type_='unique')
        # Restored using the exact original name (removed batch_op.f() and extra kwargs)
        batch_op.create_unique_constraint('vaults_name_key', ['name'])